#!/usr/bin/env python3
"""Validate the visual and research product contract for one Skill run."""

from __future__ import annotations

import argparse
import csv
import json
import struct
from pathlib import Path


FORBIDDEN_VISUAL_MARKERS = (
    "ai生成", "ai generated", "generated by ai", "openai", "chatgpt",
    "midjourney", "claude", "gemini", "stable diffusion",
)


def fail(message: str) -> None:
    raise SystemExit(f"Product validation failed: {message}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--require-feedback", action="store_true")
    args = parser.parse_args()
    root = Path(args.output_dir).expanduser().resolve()

    required = [
        "report.png", "report.html", "report.json", "data_collection.csv",
        "evidence_table.csv", "data_manifest.json", "internal/evidence.json",
        "internal/score.json",
    ]
    if args.require_feedback:
        required.append("feedback.json")
    missing = [name for name in required if not (root / name).exists() or (root / name).stat().st_size == 0]
    if missing:
        fail("missing files: " + ", ".join(missing))

    png = (root / "report.png").read_bytes()
    if len(png) < 24 or png[:8] != b"\x89PNG\r\n\x1a\n":
        fail("report.png is not a valid PNG")
    dimensions = struct.unpack(">II", png[16:24])
    if dimensions != (900, 1200):
        fail(f"report.png is {dimensions}, expected 900x1200")

    html = (root / "report.html").read_text(encoding="utf-8").lower()
    found_markers = [marker for marker in FORBIDDEN_VISUAL_MARKERS if marker in html]
    if found_markers:
        fail("AI watermark/branding markers found in poster HTML: " + ", ".join(found_markers))
    if "http://" in html or "https://" in html:
        fail("poster HTML contains external resources; all assets must be bundled")

    with (root / "data_collection.csv").open(encoding="utf-8-sig", newline="") as handle:
        collection_rows = list(csv.DictReader(handle))
    if len(collection_rows) != 1:
        fail(f"data_collection.csv must contain one user row, found {len(collection_rows)}")

    with (root / "evidence_table.csv").open(encoding="utf-8-sig", newline="") as handle:
        evidence_rows = list(csv.DictReader(handle))
    white_count = sum(row.get("group") == "W_scoring_metric" for row in evidence_rows)
    gray_count = sum(row.get("group") == "G_research_candidate" for row in evidence_rows)
    if white_count < 18 or gray_count < 19:
        fail(f"evidence table is incomplete: W={white_count}, G={gray_count}")

    manifest = json.loads((root / "data_manifest.json").read_text(encoding="utf-8"))
    expected_feedback = "collected" if args.require_feedback else "pending_user_response"
    if manifest.get("feedback_status") != expected_feedback:
        fail(f"feedback_status is {manifest.get('feedback_status')}, expected {expected_feedback}")

    print(json.dumps({
        "status": "complete" if args.require_feedback else "awaiting_feedback",
        "report_dimensions": list(dimensions),
        "ai_watermark_markers": [],
        "data_collection_rows": 1,
        "data_collection_columns": len(collection_rows[0]),
        "white_metric_rows": white_count,
        "gray_feature_rows": gray_count,
        "feedback_status": manifest["feedback_status"],
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
